version: '3.9'

services:
  mail:
    build: .
    restart: always
    ports:
      - 3003:3003
      - 50053:50053
    depends_on:
      - zipkin
      - otel-collector
  
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411 

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.62.1
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker-config/otel/otel.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    depends_on:
      - zipkin

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./docker-config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: collector.grafana
    image: grafana/grafana:9.1.7
    ports:
      - "3000:3000"
    volumes:
      - ./docker-config/prometheus/prometheus_ds.yaml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
    depends_on:
      - prometheus 